configured_endpoints: 59
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dinari--inc-dash%2Fdinari-84534cbd11b0afe0fb206eebc5ce287fe4a180bde24b4cb62ce91aeb2fcbbf47.yml
openapi_spec_hash: 47f12f37a4d8a1f952a464aa74aebf5f
config_hash: 32b40411de4c70756c6cbd6e177c8ccc
